### ISSUE TITLE
component names should make sense for the app

### ISSUE THREAD

**Issue by austin-rt** [AlaysiaVeal/Anima-List#2]
https://github.com/AlaysiaVeal/Anima-List/blob/26970759a96917b87937f4bbaf1e4e3d0b678ffb/client/src/components/ViewGameDetails.js

**Comment by AlaysiaVeal** [comment]
> https://github.com/AlaysiaVeal/Anima-List/blob/26970759a96917b87937f4bbaf1e4e3d0b678ffb/client/src/components/ViewGameDetails.js
Thank you for calling my attention to a couple of issues in my project! I changed them just so I remember the next time I turn in a project even if it doesn't change the grade you give the project.
